// Generated by tools/oka-world/build_art.py. Sizes are stored pixels; divide by STORE for scene units.
/* eslint-disable */
export const STORE = 2;

export interface TerrainFrame {
    x: number;
    y: number;
    w: number;
    h: number;
    top?: number;
    profile: (number | null)[];
}

export interface SheetInfo {
    fw: number;
    fh: number;
    frames: number;
    ax: number;
}

export const LAYERS = {"backdrop": [1280, 720], "mid": [960, 540], "near": [1280, 720]};

export const TERRAIN: Record<string, TerrainFrame> = {
    "ground": {
        "x": 851,
        "y": 0,
        "w": 840,
        "h": 302,
        "top": 2.5,
        "profile": [
            21.5,
            12.5,
            4.0,
            1.5,
            1.5,
            0.8,
            1.0,
            1.5,
            1.5,
            1.0,
            1.8,
            1.5,
            1.5,
            1.0,
            2.0,
            2.0,
            1.0,
            1.5,
            2.5,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.5,
            2.5,
            2.0,
            1.5,
            1.5,
            1.0,
            1.2,
            1.5,
            1.5,
            1.5,
            2.5,
            1.5,
            0.0,
            0.5,
            1.0,
            1.8,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.5,
            1.5,
            2.5,
            11.2,
            19.8,
            27.8
        ]
    },
    "slab": {
        "x": 972,
        "y": 804,
        "w": 800,
        "h": 83,
        "top": 3.0,
        "profile": [
            8.5,
            3.8,
            2.0,
            1.5,
            1.5,
            1.5,
            2.0,
            1.5,
            1.5,
            1.5,
            1.5,
            2.0,
            1.5,
            1.0,
            1.0,
            1.0,
            1.0,
            1.0,
            1.2,
            1.8,
            1.0,
            0.5,
            1.0,
            1.5,
            2.0,
            2.0,
            1.5,
            1.0,
            0.5,
            0.2,
            0.5,
            1.5,
            2.0,
            2.5,
            1.5,
            1.5,
            1.5,
            1.5,
            1.5,
            1.5,
            1.5,
            2.0,
            2.0,
            2.0,
            2.0,
            2.2,
            2.5,
            2.5,
            3.0,
            7.8
        ]
    },
    "floatS": {
        "x": 748,
        "y": 804,
        "w": 220,
        "h": 115,
        "top": 5.0,
        "profile": [
            6.5,
            4.5,
            3.5,
            2.5,
            2.5,
            2.5,
            1.8,
            1.0,
            2.5,
            2.2,
            2.5,
            4.0,
            5.5,
            8.0
        ]
    },
    "floatM": {
        "x": 424,
        "y": 804,
        "w": 320,
        "h": 150,
        "top": 7.0,
        "profile": [
            10.2,
            7.5,
            5.5,
            4.5,
            2.5,
            3.5,
            4.0,
            3.0,
            3.8,
            4.0,
            2.8,
            1.5,
            2.5,
            3.5,
            3.5,
            3.0,
            4.0,
            5.0,
            5.5,
            8.5
        ]
    },
    "floatL": {
        "x": 0,
        "y": 804,
        "w": 420,
        "h": 160,
        "top": 7.0,
        "profile": [
            6.8,
            5.0,
            5.0,
            5.0,
            3.5,
            3.0,
            3.5,
            3.5,
            4.0,
            4.0,
            3.0,
            2.0,
            3.0,
            1.5,
            3.2,
            3.0,
            2.8,
            3.0,
            3.0,
            3.0,
            4.0,
            4.0,
            4.2,
            5.0,
            5.0,
            5.5,
            8.2
        ]
    },
    "isle": {
        "x": 207,
        "y": 0,
        "w": 640,
        "h": 797,
        "top": 538.5,
        "profile": [
            277.0,
            272.5,
            270.0,
            267.0,
            259.8,
            254.5,
            250.8,
            244.8,
            235.0,
            230.2,
            221.0,
            224.5,
            220.2,
            213.8,
            209.0,
            211.5,
            204.5,
            202.2,
            195.5,
            189.5,
            185.0,
            183.0,
            183.0,
            183.0,
            183.0,
            183.0,
            204.5,
            212.2,
            216.2,
            223.2,
            231.8,
            234.2,
            239.2,
            244.8,
            251.2,
            263.0,
            265.0,
            268.8,
            272.8,
            276.0
        ]
    },
    "wall": {
        "x": 0,
        "y": 0,
        "w": 203,
        "h": 800,
        "top": 4.0,
        "profile": [
            9.8,
            2.5,
            1.2,
            1.0,
            2.5,
            2.0,
            2.0,
            1.5,
            1.5,
            1.5,
            2.5,
            3.5,
            381.0
        ]
    }
};

export const SHEETS: Record<string, SheetInfo> = {
    "mori": {
        "fw": 165,
        "fh": 148,
        "frames": 8,
        "ax": 104
    },
    "mossback": {
        "fw": 196,
        "fh": 158,
        "frames": 4,
        "ax": 98
    },
    "glimmerfly": {
        "fw": 130,
        "fh": 144,
        "frames": 4,
        "ax": 65
    },
    "gloomfin": {
        "fw": 176,
        "fh": 146,
        "frames": 4,
        "ax": 88
    }
};

export const ITEMS: Record<string, { w: number; h: number }> = {
    "BlueCrystal": {
        "w": 31,
        "h": 60
    },
    "HeartMoss": {
        "w": 68,
        "h": 64
    },
    "Heartstone": {
        "w": 152,
        "h": 200
    },
    "BonsaiTree": {
        "w": 328,
        "h": 480
    },
    "Boulders": {
        "w": 220,
        "h": 162
    },
    "MossyBoulder": {
        "w": 240,
        "h": 175
    },
    "Kelp": {
        "w": 128,
        "h": 192
    },
    "Fern": {
        "w": 184,
        "h": 140
    },
    "MossDrip": {
        "w": 240,
        "h": 125
    },
    "GrassTuft": {
        "w": 128,
        "h": 51
    },
    "GlowShrooms": {
        "w": 101,
        "h": 92
    },
    "Stalagmite": {
        "w": 115,
        "h": 144
    }
};
