// Generated by build-sprites.mjs. Do not edit by hand.
export interface Frame {
    x: number;
    y: number;
    w: number;
    h: number;
}

export const FONT_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ:-x ";

export const frames: Record<string, Frame> = {
    "ground": {
        "x": 0,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "dirt": {
        "x": 18,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "brick": {
        "x": 36,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "brick-blue": {
        "x": 54,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "question-0": {
        "x": 72,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "question-1": {
        "x": 90,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "question-2": {
        "x": 108,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "used": {
        "x": 126,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "hard": {
        "x": 144,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pipe-tl": {
        "x": 162,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pipe-tr": {
        "x": 180,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pipe-bl": {
        "x": 198,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pipe-br": {
        "x": 216,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pip-idle": {
        "x": 234,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pip-walk-0": {
        "x": 252,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pip-walk-1": {
        "x": 270,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pip-walk-2": {
        "x": 288,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pip-jump": {
        "x": 306,
        "y": 0,
        "w": 16,
        "h": 16
    },
    "pip-skid": {
        "x": 0,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "pip-crouch": {
        "x": 18,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "pip-dead": {
        "x": 36,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "pip-big-idle": {
        "x": 54,
        "y": 18,
        "w": 16,
        "h": 32
    },
    "pip-big-walk-0": {
        "x": 72,
        "y": 18,
        "w": 16,
        "h": 32
    },
    "pip-big-walk-1": {
        "x": 90,
        "y": 18,
        "w": 16,
        "h": 32
    },
    "pip-big-walk-2": {
        "x": 108,
        "y": 18,
        "w": 16,
        "h": 32
    },
    "pip-big-jump": {
        "x": 126,
        "y": 18,
        "w": 16,
        "h": 32
    },
    "pip-big-skid": {
        "x": 144,
        "y": 18,
        "w": 16,
        "h": 32
    },
    "pip-big-crouch": {
        "x": 162,
        "y": 18,
        "w": 16,
        "h": 32
    },
    "sprout-0": {
        "x": 180,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "sprout-1": {
        "x": 198,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "sprout-flat": {
        "x": 216,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "shellkin-0": {
        "x": 234,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "shellkin-1": {
        "x": 252,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "shellkin-shell": {
        "x": 270,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "coin-0": {
        "x": 288,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "coin-1": {
        "x": 306,
        "y": 18,
        "w": 16,
        "h": 16
    },
    "coin-2": {
        "x": 0,
        "y": 52,
        "w": 16,
        "h": 16
    },
    "coin-icon": {
        "x": 18,
        "y": 52,
        "w": 8,
        "h": 8
    },
    "fruit": {
        "x": 28,
        "y": 52,
        "w": 16,
        "h": 16
    },
    "fruit-life": {
        "x": 46,
        "y": 52,
        "w": 16,
        "h": 16
    },
    "star-0": {
        "x": 64,
        "y": 52,
        "w": 16,
        "h": 16
    },
    "star-1": {
        "x": 82,
        "y": 52,
        "w": 16,
        "h": 16
    },
    "shard": {
        "x": 100,
        "y": 52,
        "w": 3,
        "h": 3
    },
    "flag": {
        "x": 105,
        "y": 52,
        "w": 16,
        "h": 16
    },
    "pole": {
        "x": 123,
        "y": 52,
        "w": 16,
        "h": 16
    },
    "cloud-a": {
        "x": 141,
        "y": 52,
        "w": 46,
        "h": 24
    },
    "cloud-b": {
        "x": 189,
        "y": 52,
        "w": 32,
        "h": 20
    },
    "hill-lg": {
        "x": 223,
        "y": 52,
        "w": 80,
        "h": 36
    },
    "hill-sm": {
        "x": 0,
        "y": 90,
        "w": 48,
        "h": 22
    },
    "bush-a": {
        "x": 50,
        "y": 90,
        "w": 46,
        "h": 18
    },
    "bush-b": {
        "x": 98,
        "y": 90,
        "w": 30,
        "h": 16
    },
    "castle": {
        "x": 130,
        "y": 90,
        "w": 80,
        "h": 80
    },
    "font": {
        "x": 0,
        "y": 172,
        "w": 320,
        "h": 8
    }
};
